export const schemaSdlFixture = `"""
Relationship entity for the ACTED_IN edge between Actor and Movie.
"""
type ActedIn @relationshipProperties {
  """
  The actor involved in the relationship.
  """
  actor: ID!

  """
  The movie involved in the relationship.
  """
  movie: ID!

  """
  The specific character names the actor played in this movie.
  """
  roles: [String!]!
}

"""
Relationship entity for the ACTED_IN edge between Actor and Series.
"""
type ActedInSeries @relationshipProperties {
  """
  The actor involved in the relationship.
  """
  actor: ID!

  """
  The series involved in the relationship.
  """
  series: ID!

  """
  The specific character names the actor played in this series.
  """
  roles: [String!]!
}

"""
Represents a performer in the entertainment industry.
"""
type Actor @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The actor's professional name.
  """
  name: String!

  """
  The year the actor was born.
  """
  born: Int!

  series: [Series!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedInSeries")

  movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

type Address {
  """
  The street name and number of the address.
  """
  street: String!

  """
  The city of the address.
  """
  city: String!

  """
  The postal code of the address.
  """
  zipCode: String!
}

"""
Represents a grouping for products.
Maps to a (:Category) node in Neo4j.
"""
type Category @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The human-readable name of the category (e.g., 'Electronics').
  """
  categoryName: String!

  products: [Product!]! @relationship(type: "PART_OF", direction: IN)
}

"""
A virtual entity (View) providing a summary of product counts per category.
"""
type CategorySummary {
  """
  Name of the category being summarized.
  """
  categoryName: String!

  """
  The total number of products linked to this category.
  """
  totalProducts: Int!
}

"""
A specialized Person type representing high-level staff with dual labels.
"""
type Executive @node(labels: ["Employee", "Manager"]) {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The executive's name.
  """
  name: String!

  """
  The corporate title (e.g., 'VP of Engineering').
  """
  title: String!

  """
  The specific business unit they oversee.
  """
  department: String!
}

"""
Relationship entity for the FRIENDS_WITH edge between two Users.
"""
type FriendsWith @relationshipProperties {
  """
  The initiating user of the friendship.
  """
  user1: ID!

  """
  The receiving user of the friendship.
  """
  user2: ID!

  """
  The year the friendship began.
  """
  since: Int!

  """
  A numerical value representing the closeness of the friendship.
  """
  strength: Int!
}

"""
Represents a feature-length film.
"""
type Movie @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The official title of the movie.
  """
  title: String!

  """
  The year the movie was released.
  """
  released: Int!

  """
  A short marketing catchphrase for the movie.
  """
  tagline: String

  actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
}

"""
Represents a human entity in a social or professional graph.
"""
type Person @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The person's full name.
  """
  name: String!

  """
  The person's age in years.
  """
  age: Int!

  """
  The physical address of the person.
  """
  address: Address

  knows: [Person!]! @relationship(type: "KNOWS", direction: OUT)

  colleagues: [Person!]! @relationship(type: "WORKS_WITH", direction: OUT)
}

"""
Represents an individual item for sale.
Maps to a (:Product) node in Neo4j.
"""
type Product @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The name of the product.
  """
  productName: String!

  """
  The cost of the product.
  """
  price: Int

  tags: [Tag!]! @relationship(type: "HAS_TAG", direction: OUT)

  category: [Category!]! @relationship(type: "PART_OF", direction: OUT)
}

"""
A virtual entity using QueryBuilder to return flattened product/category data.
"""
type ProductWithCategory {
  """
  The name of the product.
  """
  productName: String!

  """
  The name of the associated category.
  """
  categoryName: String!

  """
  The price of the product.
  """
  price: Int
}

type Query {
  """
  A virtual entity using QueryBuilder to return flattened product/category data.
  """
  productsWithCategory(limit: Int, orderByPriceDesc: Boolean): [ProductWithCategory!]!

  """
  A virtual entity (View) providing a summary of product counts per category.
  """
  categorySummaries: [CategorySummary!]! @cypher(statement: """
  MATCH (c:category) RETURN { categoryName: c.categoryName, totalProducts: COUNT { (c)<-[:PART_OF]-(:product) } }
  """, columnName: "this")
}

"""
Represents a television or streaming series.
"""
type Series @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The official title of the series.
  """
  title: String!

  """
  The year the first season was released.
  """
  released: Int!

  """
  The total count of episodes produced.
  """
  episodes: Int!

  actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedInSeries")
}

"""
A metadata label used to organize products. Maps to a (:Tag) node.
"""
type Tag @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The label name (e.g., On Sale, New Arrival).
  """
  name: String!

  products: [Product!]! @relationship(type: "HAS_TAG", direction: IN)
}

"""
Represents a platform account holder.
"""
type User @node {
  """
  The internal unique identifier, auto-generated by the database.
  """
  id: ID! @id

  """
  The user's unique display name.
  """
  username: String!

  """
  The user's registered email address.
  """
  email: String!

  friends: [User!]! @relationship(type: "FRIENDS_WITH", direction: OUT, properties: "FriendsWith")
}`;
